<?php
use App\Config\Config;
use App\Helpers\Session;
use App\Middleware\Auth;
require_once __DIR__ . '/../../Partials/header.php';
require_once __DIR__ . '/../Partials/navbar.php';
$solicitudes=$solicitudes??[]; $instituciones=$instituciones??[]; $catalogo=$catalogo??[];
$estados=$estados??[]; $buscar=$buscar??''; $estado=$estado??''; $catalogoBuscar=$catalogoBuscar??'';
$puedeGestionar=Auth::tienePermiso('interbibliotecario.gestionar');
$esc=static fn(mixed $v):string=>htmlspecialchars((string)($v??''),ENT_QUOTES,'UTF-8');
$success=Session::getFlash('success'); $error=Session::getFlash('error');
?>
<div class="container-fluid admin-page"><div class="row">
<div class="col-md-2 p-0"><?php require __DIR__.'/../Partials/sidebar.php'; ?></div>
<main class="col-md-10 admin-main">
<div class="admin-page-header d-flex justify-content-between align-items-center gap-3"><div><h2 class="mb-1">Préstamo interbibliotecario</h2><p class="text-muted mb-0">Gestiona instituciones, catálogo externo y solicitudes de usuarios.</p></div><span class="badge bg-dark"><?=count($solicitudes)?> solicitudes</span></div>
<?php if($success):?><div class="alert alert-success"><?=$esc($success)?></div><?php endif;?>
<?php if($error):?><div class="alert alert-danger"><?=$esc($error)?></div><?php endif;?>
<div class="card admin-list-card mb-4"><div class="admin-card-heading"><div><h3 class="admin-card-title mb-1">Solicitudes</h3><p class="mb-0">Aprueba, recibe, devuelve o rechaza préstamos de otras bibliotecas.</p></div></div>
<form method="GET" action="<?=Config::url('interbibliotecario')?>" class="row g-3 admin-filter-form"><div class="col-md-7"><input class="form-control" name="buscar" value="<?=$esc($buscar)?>" placeholder="Libro, autor, institución o usuario"></div><div class="col-md-3"><select class="form-select" name="estado"><option value="">Todos los estados</option><?php foreach($estados as $e):?><option value="<?=$esc($e)?>" <?=$estado===$e?'selected':''?>><?=$esc($e)?></option><?php endforeach;?></select></div><div class="col-md-2 d-grid"><button class="btn btn-primary"><i class="fa-solid fa-filter"></i> Filtrar</button></div></form>
<div class="table-responsive"><table class="table table-hover align-middle admin-table"><thead><tr><th>Usuario</th><th>Libro externo</th><th>Institución</th><th>Fechas</th><th>Estado</th><th>Gestión</th></tr></thead><tbody>
<?php foreach($solicitudes as $s):?><tr><td><strong><?=$esc($s['usuario_nombre'])?></strong><div class="small text-muted"><?=$esc($s['tipo_usuario'])?> · <?=$esc($s['usuario'])?></div></td><td><strong><?=$esc($s['titulo'])?></strong><div class="small text-muted"><?=$esc($s['autor'])?><?=!empty($s['isbn'])?' · ISBN '.$esc($s['isbn']):''?></div></td><td><?=$esc($s['institucion'])?></td><td><small>Solicitud: <?=$esc(substr((string)$s['fecha_solicitud'],0,10))?><br>Vence: <?=$esc($s['fecha_vencimiento']?:'Sin definir')?></small></td><td><span class="badge bg-<?=in_array($s['estado'],['Aprobado','Recibido'],true)?'success':(in_array($s['estado'],['Rechazado','Cancelado'],true)?'danger':'warning')?>"><?=$esc($s['estado'])?></span></td><td style="min-width:310px"><?php if($puedeGestionar):?><form method="POST" action="<?=Config::url('interbibliotecario/solicitud/actualizar')?>" class="row g-2"><input type="hidden" name="id_solicitud" value="<?=(int)$s['id_prestamo_interbibliotecario']?>"><div class="col-5"><select class="form-select form-select-sm" name="estado"><?php foreach($estados as $e):?><option value="<?=$esc($e)?>" <?=$s['estado']===$e?'selected':''?>><?=$esc($e)?></option><?php endforeach;?></select></div><div class="col-5"><input type="date" class="form-control form-control-sm" name="fecha_vencimiento" value="<?=$esc($s['fecha_vencimiento'])?>"></div><div class="col-2 d-grid"><button class="btn btn-sm btn-primary" title="Guardar"><i class="fa-solid fa-floppy-disk"></i></button></div><div class="col-12"><input class="form-control form-control-sm" name="observacion" value="<?=$esc($s['observacion'])?>" placeholder="Observación administrativa"></div></form><?php else:?>—<?php endif;?></td></tr><?php endforeach;?>
<?php if(!$solicitudes):?><tr><td colspan="6" class="text-center py-4">No hay solicitudes con esos filtros.</td></tr><?php endif;?></tbody></table></div></div>
<div class="row g-4"><div class="col-xl-5"><div class="card admin-list-card h-100"><div class="admin-card-heading"><div><h3 class="admin-card-title mb-1">Instituciones aliadas</h3><p class="mb-0">Bibliotecas que prestan su catálogo.</p></div></div>
<?php if($puedeGestionar):?><form method="POST" action="<?=Config::url('interbibliotecario/institucion/guardar')?>" class="row g-2 p-3 border-bottom"><input type="hidden" name="id_institucion" id="inst_id" value="0"><div class="col-12"><input required class="form-control" name="nombre" id="inst_nombre" placeholder="Nombre de la institución"></div><div class="col-12"><input class="form-control" name="direccion" id="inst_direccion" placeholder="Dirección"></div><div class="col-6"><input class="form-control" name="telefono" id="inst_telefono" placeholder="Teléfono"></div><div class="col-6"><input type="email" class="form-control" name="correo" id="inst_correo" placeholder="Correo"></div><div class="col-8"><input type="url" class="form-control" name="sitio_web" id="inst_web" placeholder="https://..."></div><div class="col-4 d-grid"><button class="btn btn-primary">Guardar</button></div></form><?php endif;?>
<div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Institución</th><th>Estado</th><th></th></tr></thead><tbody><?php foreach($instituciones as $i):?><tr><td><strong><?=$esc($i['nombre'])?></strong><div class="small text-muted"><?=$esc($i['correo']?:$i['telefono'])?></div></td><td><span class="badge bg-<?=(int)$i['estado']===1?'success':'secondary'?>"><?=(int)$i['estado']===1?'Activa':'Inactiva'?></span></td><td><?php if($puedeGestionar):?><button type="button" class="btn btn-sm btn-warning" onclick='editarInstitucion(<?=json_encode($i,JSON_HEX_APOS|JSON_HEX_QUOT)?>)'>Editar</button><form method="POST" action="<?=Config::url('interbibliotecario/institucion/estado')?>" class="d-inline"><input type="hidden" name="id_institucion" value="<?=(int)$i['id_institucion']?>"><input type="hidden" name="estado" value="<?=(int)$i['estado']===1?0:1?>"><button class="btn btn-sm btn-outline-dark"><?=(int)$i['estado']===1?'Desactivar':'Activar'?></button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div></div>
<div class="col-xl-7"><div class="card admin-list-card h-100"><div class="admin-card-heading"><div><h3 class="admin-card-title mb-1">Catálogo externo</h3><p class="mb-0">Títulos disponibles en otras instituciones.</p></div></div>
<?php if($puedeGestionar):?><form method="POST" action="<?=Config::url('interbibliotecario/libro/guardar')?>" class="row g-2 p-3 border-bottom"><input type="hidden" name="id_libro_externo" id="ext_id" value="0"><div class="col-md-4"><select required class="form-select" name="id_institucion" id="ext_institucion"><option value="">Institución</option><?php foreach($instituciones as $i):?><option value="<?=(int)$i['id_institucion']?>"><?=$esc($i['nombre'])?></option><?php endforeach;?></select></div><div class="col-md-4"><input required class="form-control" name="titulo" id="ext_titulo" placeholder="Título"></div><div class="col-md-4"><input required class="form-control" name="autor" id="ext_autor" placeholder="Autor"></div><div class="col-md-3"><input class="form-control" name="isbn" id="ext_isbn" placeholder="ISBN"></div><div class="col-md-5"><input type="url" class="form-control" name="url_catalogo" id="ext_url" placeholder="Enlace del catálogo"></div><div class="col-md-4 d-grid"><button class="btn btn-primary">Guardar libro</button></div><div class="col-12"><textarea class="form-control" name="descripcion" id="ext_descripcion" rows="2" placeholder="Descripción"></textarea></div></form><?php endif;?>
<form method="GET" action="<?=Config::url('interbibliotecario')?>" class="p-3 d-flex gap-2"><input class="form-control" name="catalogo" value="<?=$esc($catalogoBuscar)?>" placeholder="Buscar catálogo externo"><button class="btn btn-outline-primary">Buscar</button></form><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Libro</th><th>Institución</th><th>Disponible</th><th></th></tr></thead><tbody><?php foreach($catalogo as $l):?><tr><td><strong><?=$esc($l['titulo'])?></strong><div class="small text-muted"><?=$esc($l['autor'])?></div></td><td><?=$esc($l['institucion'])?></td><td><span class="badge bg-<?=(int)$l['disponible']===1?'success':'secondary'?>"><?=(int)$l['disponible']===1?'Sí':'No'?></span></td><td><?php if($puedeGestionar):?><button type="button" class="btn btn-sm btn-warning" onclick='editarLibroExterno(<?=json_encode($l,JSON_HEX_APOS|JSON_HEX_QUOT)?>)'>Editar</button><form method="POST" action="<?=Config::url('interbibliotecario/libro/disponibilidad')?>" class="d-inline"><input type="hidden" name="id_libro_externo" value="<?=(int)$l['id_libro_externo']?>"><input type="hidden" name="disponible" value="<?=(int)$l['disponible']===1?0:1?>"><button class="btn btn-sm btn-outline-dark"><?=(int)$l['disponible']===1?'No disponible':'Disponible'?></button></form><?php endif;?></td></tr><?php endforeach;?><?php if(!$catalogo):?><tr><td colspan="4" class="text-center py-4">No hay libros externos.</td></tr><?php endif;?></tbody></table></div></div></div></div>
</main></div></div>
<script>
function editarInstitucion(i){for(const[k,v]of Object.entries({inst_id:i.id_institucion,inst_nombre:i.nombre,inst_direccion:i.direccion,inst_telefono:i.telefono,inst_correo:i.correo,inst_web:i.sitio_web})){const e=document.getElementById(k);if(e)e.value=v||'';}document.getElementById('inst_nombre').scrollIntoView({behavior:'smooth',block:'center'});}
function editarLibroExterno(l){for(const[k,v]of Object.entries({ext_id:l.id_libro_externo,ext_institucion:l.id_institucion,ext_titulo:l.titulo,ext_autor:l.autor,ext_isbn:l.isbn,ext_url:l.url_catalogo,ext_descripcion:l.descripcion})){const e=document.getElementById(k);if(e)e.value=v||'';}document.getElementById('ext_titulo').scrollIntoView({behavior:'smooth',block:'center'});}
</script>
<?php require_once __DIR__.'/../../Partials/footer.php'; ?>
